# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("AES算法CBC模式演示")
        MainWindow.resize(946, 600)
        MainWindow.setStyleSheet("background-color: rgb(108, 218, 163);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.D3Button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.D3Button_4.setGeometry(QtCore.QRect(640, 331, 81, 20))
        self.D3Button_4.setStyleSheet("background-color:rgb(222, 225, 255)")
        self.D3Button_4.setObjectName("D3Button_4")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(280, 140, 16, 41))
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(470, 210, 20, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(260, 420, 71, 16))
        self.label_14.setObjectName("label_14")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(470, 140, 20, 41))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.C2 = QtWidgets.QLineEdit(self.centralwidget)
        self.C2.setGeometry(QtCore.QRect(420, 260, 113, 20))
        self.C2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C2.setObjectName("C2")
        self.C3 = QtWidgets.QLineEdit(self.centralwidget)
        self.C3.setGeometry(QtCore.QRect(620, 260, 113, 20))
        self.C3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C3.setObjectName("C3")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(820, 100, 71, 21))
        self.label_13.setObjectName("label_13")
        self.wordp1 = QtWidgets.QFrame(self.centralwidget)
        self.wordp1.setGeometry(QtCore.QRect(180, 180, 61, 21))
        self.wordp1.setFrameShape(QtWidgets.QFrame.HLine)
        self.wordp1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.wordp1.setObjectName("wordp1")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(450, 240, 71, 20))
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 30, 311, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 61, 21))
        self.label_2.setStyleSheet("font: 75 16pt \"华文仿宋\";")
        self.label_2.setObjectName("label_2")
        self.D1Button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.D1Button_6.setGeometry(QtCore.QRect(250, 331, 81, 20))
        self.D1Button_6.setStyleSheet("background-color:rgb(222, 225, 255)")
        self.D1Button_6.setObjectName("D1Button_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 270, 61, 21))
        self.label_10.setStyleSheet("font: 75 16pt \"华文仿宋\";")
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(160, 150, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 100, 71, 16))
        self.label_4.setObjectName("label_4")
        self.P1 = QtWidgets.QLineEdit(self.centralwidget)
        self.P1.setGeometry(QtCore.QRect(230, 120, 113, 20))
        self.P1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.P1.setObjectName("P1")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(650, 420, 71, 16))
        self.label_12.setObjectName("label_12")
        self.E4Button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.E4Button_7.setGeometry(QtCore.QRect(820, 181, 81, 20))
        self.E4Button_7.setStyleSheet("background-color:rgb(222, 225, 255)")
        self.E4Button_7.setObjectName("E4Button_7")
        self.AP2 = QtWidgets.QLineEdit(self.centralwidget)
        self.AP2.setGeometry(QtCore.QRect(420, 400, 113, 20))
        self.AP2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.AP2.setObjectName("AP2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 100, 71, 16))
        self.label_3.setObjectName("label_3")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(670, 140, 20, 41))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(280, 210, 20, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(650, 240, 71, 16))
        self.label_8.setObjectName("label_8")
        self.AP1 = QtWidgets.QLineEdit(self.centralwidget)
        self.AP1.setGeometry(QtCore.QRect(230, 400, 113, 20))
        self.AP1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.AP1.setObjectName("AP1")
        self.C4 = QtWidgets.QLineEdit(self.centralwidget)
        self.C4.setGeometry(QtCore.QRect(800, 260, 113, 20))
        self.C4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C4.setObjectName("C4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(450, 420, 71, 20))
        self.label_11.setObjectName("label_11")
        self.AP4 = QtWidgets.QLineEdit(self.centralwidget)
        self.AP4.setGeometry(QtCore.QRect(800, 400, 113, 20))
        self.AP4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.AP4.setObjectName("AP4")
        self.E2Button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.E2Button_2.setGeometry(QtCore.QRect(440, 180, 75, 23))
        self.E2Button_2.setStyleSheet("background-color:rgb(222, 225, 255)")
        self.E2Button_2.setObjectName("E2Button_2")
        self.P2 = QtWidgets.QLineEdit(self.centralwidget)
        self.P2.setGeometry(QtCore.QRect(420, 120, 113, 20))
        self.P2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.P2.setObjectName("P2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(640, 100, 71, 21))
        self.label_5.setObjectName("label_5")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(670, 210, 16, 31))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.Dkey = QtWidgets.QLineEdit(self.centralwidget)
        self.Dkey.setGeometry(QtCore.QRect(90, 330, 81, 21))
        self.Dkey.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Dkey.setObjectName("Dkey")
        self.E1Button = QtWidgets.QPushButton(self.centralwidget)
        self.E1Button.setGeometry(QtCore.QRect(250, 181, 71, 20))
        self.E1Button.setStyleSheet("background-color:rgb(222, 225, 255)")
        self.E1Button.setObjectName("E1Button")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(850, 210, 16, 31))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.P4 = QtWidgets.QLineEdit(self.centralwidget)
        self.P4.setGeometry(QtCore.QRect(800, 120, 113, 20))
        self.P4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.P4.setObjectName("P4")
        self.P3 = QtWidgets.QLineEdit(self.centralwidget)
        self.P3.setGeometry(QtCore.QRect(620, 120, 113, 20))
        self.P3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.P3.setObjectName("P3")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(280, 360, 20, 31))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.D4Button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.D4Button_8.setGeometry(QtCore.QRect(820, 331, 81, 20))
        self.D4Button_8.setStyleSheet("background-color:rgb(222, 225, 255)")
        self.D4Button_8.setObjectName("D4Button_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(670, 360, 16, 31))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(470, 360, 20, 31))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(180, 330, 61, 21))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(470, 280, 20, 51))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.C1 = QtWidgets.QLineEdit(self.centralwidget)
        self.C1.setGeometry(QtCore.QRect(230, 260, 113, 20))
        self.C1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C1.setObjectName("C1")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(280, 280, 16, 51))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.Ekey = QtWidgets.QLineEdit(self.centralwidget)
        self.Ekey.setGeometry(QtCore.QRect(90, 180, 81, 21))
        self.Ekey.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Ekey.setObjectName("Ekey")
        self.E3Button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.E3Button_3.setGeometry(QtCore.QRect(640, 180, 81, 21))
        self.E3Button_3.setStyleSheet("background-color:rgb(222, 225, 255)")
        self.E3Button_3.setObjectName("E3Button_3")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(850, 140, 20, 41))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 240, 71, 16))
        self.label_6.setObjectName("label_6")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(850, 360, 16, 31))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(830, 420, 71, 16))
        self.label_17.setObjectName("label_17")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(160, 310, 71, 16))
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(70, 470, 311, 31))
        self.label_18.setObjectName("label_18")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(830, 240, 71, 16))
        self.label_16.setObjectName("label_16")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(850, 280, 20, 51))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.AP3 = QtWidgets.QLineEdit(self.centralwidget)
        self.AP3.setGeometry(QtCore.QRect(620, 400, 113, 20))
        self.AP3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.AP3.setObjectName("AP3")
        self.D2Button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.D2Button_5.setGeometry(QtCore.QRect(440, 330, 75, 23))
        self.D2Button_5.setStyleSheet("background-color:rgb(222, 225, 255)")
        self.D2Button_5.setObjectName("D2Button_5")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(670, 280, 20, 51))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 946, 23))
        self.menubar.setObjectName("menubar")

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AES算法CBC模式演示"))
        self.D3Button_4.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">分组加密</span></p></body></html>"))
        self.D3Button_4.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">分组加密</span></p></body></html>"))
        self.D3Button_4.setText(_translate("MainWindow", "分组解密"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">明文分组P1</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">明文分组P4</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">密文分组C2</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">AES算法EBC模式演示程序</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">加密</span></p></body></html>"))
        self.D1Button_6.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">分组加密</span></p></body></html>"))
        self.D1Button_6.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">分组解密</span></p></body></html>"))
        self.D1Button_6.setText(_translate("MainWindow", "分组解密"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">解密</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">秘钥key</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">明文分组P2</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">明文分组P3</span></p></body></html>"))
        self.E4Button_7.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">分组加密</span></p></body></html>"))
        self.E4Button_7.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">分组加密</span></p></body></html>"))
        self.E4Button_7.setText(_translate("MainWindow", "分组加密"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">明文分组P1</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">密文分组C3</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">明文分组P2</span></p></body></html>"))
        self.E2Button_2.setText(_translate("MainWindow", "分组加密"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">明文分组P3</span></p></body></html>"))
        self.E1Button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">分组加密</span></p></body></html>"))
        self.E1Button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">分组加密</span></p></body></html>"))
        self.E1Button.setText(_translate("MainWindow", "分组加密"))
        self.D4Button_8.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">分组加密</span></p></body></html>"))
        self.D4Button_8.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">分组加密</span></p></body></html>"))
        self.D4Button_8.setText(_translate("MainWindow", "分组解密"))
        self.E3Button_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">分组加密</span></p></body></html>"))
        self.E3Button_3.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">分组加密</span></p></body></html>"))
        self.E3Button_3.setText(_translate("MainWindow", "分组加密"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">密文分组C1</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">明文分组P4</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">秘钥key</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "注意：每一分组秘钥相同，秘钥和明文分组均为16个字符"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">密文分组C4</span></p></body></html>"))
        self.D2Button_5.setText(_translate("MainWindow", "分组解密"))

        # 自定义加密槽函数





